-- ─── AgentPostmortem — Initial Schema ───────────────────────────────────────
-- Migration: 0001_init.sql
-- Run against a fresh Supabase project.
-- All tables have RLS enabled. Policies are defined below.

-- ─── Extensions ──────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- gen_random_uuid(), crypt()
CREATE EXTENSION IF NOT EXISTS "pg_trgm";   -- trigram search on titles

-- ─── Custom types ────────────────────────────────────────────────────────────
CREATE TYPE post_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE vote_direction AS ENUM ('up', 'down');
CREATE TYPE comment_status AS ENUM ('visible', 'hidden', 'removed');

-- ─── agents ──────────────────────────────────────────────────────────────────
CREATE TABLE agents (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  company     TEXT NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE agents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "agents: public read" ON agents
  FOR SELECT TO anon, authenticated USING (true);

-- ─── tags ────────────────────────────────────────────────────────────────────
CREATE TABLE tags (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT NOT NULL UNIQUE,
  label       TEXT NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tags: public read" ON tags
  FOR SELECT TO anon, authenticated USING (true);

-- ─── posts ───────────────────────────────────────────────────────────────────
CREATE TABLE posts (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Sequential human-readable case number (APM-XXXX), generated by trigger
  case_number          TEXT UNIQUE,
  title                TEXT NOT NULL CHECK (char_length(title) BETWEEN 20 AND 200),
  agent_id             UUID NOT NULL REFERENCES agents(id) ON DELETE RESTRICT,
  outcome              TEXT NOT NULL CHECK (char_length(outcome) >= 100),
  prompt               TEXT,
  damage_level         SMALLINT NOT NULL CHECK (damage_level BETWEEN 1 AND 5),
  estimated_cost_usd   INTEGER CHECK (estimated_cost_usd >= 0),
  vote_score           INTEGER NOT NULL DEFAULT 0,
  is_anonymous         BOOLEAN NOT NULL DEFAULT true,
  author_handle        TEXT,
  -- HMAC-SHA256 of submitter IP — never the raw IP
  ip_hash              TEXT NOT NULL,
  -- SHA-256 of the edit token — never the raw token
  edit_token_hash      TEXT,
  status               post_status NOT NULL DEFAULT 'pending',
  screenshots          TEXT[],
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Full-text search index on title + outcome
CREATE INDEX posts_title_trgm_idx ON posts USING GIN (title gin_trgm_ops);
CREATE INDEX posts_status_idx ON posts (status);
CREATE INDEX posts_agent_id_idx ON posts (agent_id);
CREATE INDEX posts_vote_score_idx ON posts (vote_score DESC);
CREATE INDEX posts_created_at_idx ON posts (created_at DESC);

ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Public can only read approved posts
CREATE POLICY "posts: public read approved" ON posts
  FOR SELECT TO anon, authenticated
  USING (status = 'approved');

-- Anyone can insert (submissions flow through API route that validates)
CREATE POLICY "posts: insert" ON posts
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- Only service role (via admin client) can update
CREATE POLICY "posts: service role update" ON posts
  FOR UPDATE TO service_role
  USING (true) WITH CHECK (true);

-- Auto-generate case_number on INSERT approval
CREATE SEQUENCE posts_case_number_seq START 1;

CREATE OR REPLACE FUNCTION assign_case_number()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = 'approved' AND OLD.status != 'approved' THEN
    NEW.case_number := 'APM-' || LPAD(nextval('posts_case_number_seq')::TEXT, 4, '0');
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER posts_assign_case_number
  BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION assign_case_number();

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- ─── post_tags (join table) ───────────────────────────────────────────────────
CREATE TABLE post_tags (
  post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  tag_id  UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, tag_id)
);

CREATE INDEX post_tags_tag_id_idx ON post_tags (tag_id);

ALTER TABLE post_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "post_tags: public read" ON post_tags
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "post_tags: insert" ON post_tags
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- ─── votes ───────────────────────────────────────────────────────────────────
CREATE TABLE votes (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id    UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  ip_hash    TEXT NOT NULL,
  direction  vote_direction NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- One vote per IP hash per post
  UNIQUE (post_id, ip_hash)
);

CREATE INDEX votes_post_id_idx ON votes (post_id);

ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "votes: insert" ON votes
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "votes: update own" ON votes
  FOR UPDATE TO anon, authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY "votes: delete own" ON votes
  FOR DELETE TO anon, authenticated USING (true);

-- Maintain vote_score denormalized on posts
CREATE OR REPLACE FUNCTION recalculate_vote_score()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  UPDATE posts
  SET vote_score = (
    SELECT COALESCE(
      SUM(CASE WHEN direction = 'up' THEN 1 ELSE -1 END),
      0
    )
    FROM votes
    WHERE post_id = COALESCE(NEW.post_id, OLD.post_id)
  )
  WHERE id = COALESCE(NEW.post_id, OLD.post_id);
  RETURN NULL;
END;
$$;

CREATE TRIGGER votes_update_score
  AFTER INSERT OR UPDATE OR DELETE ON votes
  FOR EACH ROW EXECUTE FUNCTION recalculate_vote_score();

-- ─── comments ────────────────────────────────────────────────────────────────
CREATE TABLE comments (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id        UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  body           TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  is_anonymous   BOOLEAN NOT NULL DEFAULT true,
  author_handle  TEXT,
  ip_hash        TEXT NOT NULL,
  status         comment_status NOT NULL DEFAULT 'visible',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX comments_post_id_idx ON comments (post_id, created_at);

ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "comments: read visible" ON comments
  FOR SELECT TO anon, authenticated
  USING (status = 'visible');

CREATE POLICY "comments: insert" ON comments
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "comments: service role update" ON comments
  FOR UPDATE TO service_role USING (true) WITH CHECK (true);

-- ─── team_waitlist ────────────────────────────────────────────────────────────
CREATE TABLE team_waitlist (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email      TEXT NOT NULL UNIQUE,
  company    TEXT NOT NULL,
  role       TEXT NOT NULL,
  use_case   TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE team_waitlist ENABLE ROW LEVEL SECURITY;

-- Only service role can read waitlist entries
CREATE POLICY "team_waitlist: insert" ON team_waitlist
  FOR INSERT TO anon, authenticated WITH CHECK (true);

-- ─── reports ─────────────────────────────────────────────────────────────────
CREATE TABLE reports (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id    UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  reason     TEXT NOT NULL CHECK (char_length(reason) BETWEEN 10 AND 500),
  ip_hash    TEXT NOT NULL,
  resolved   BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Limit one report per IP per post
  UNIQUE (post_id, ip_hash)
);

CREATE INDEX reports_resolved_idx ON reports (resolved, created_at);

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "reports: insert" ON reports
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "reports: service role read" ON reports
  FOR SELECT TO service_role USING (true);

CREATE POLICY "reports: service role update" ON reports
  FOR UPDATE TO service_role USING (true) WITH CHECK (true);
